-- This migration originally duplicated the full baseline created by
-- 20260718131500_init_hivelore_schema. Re-running those CREATE TYPE, table,
-- index, and foreign-key statements breaks fresh PostgreSQL deployments because
-- the authoritative baseline has already created the same schema objects.
--
-- Keep this migration directory so databases that have recorded the historical
-- migration name do not see a deleted migration. Its body is intentionally a
-- no-op for fresh databases and for environments that only applied the earlier
-- baseline.
