import { WorldRole as PrismaWorldRole } from '../generated/prisma/enums.js';
import type { WorldRole as PrismaWorldRoleType } from '../generated/prisma/enums.js';

export const WORLD_ROLES = PrismaWorldRole;

export type WorldRole = PrismaWorldRoleType;

export const WORLD_PERMISSIONS = {
  VIEW_PUBLIC_WORLD: 'VIEW_PUBLIC_WORLD',
  CREATE_LORE_DRAFT: 'CREATE_LORE_DRAFT',
  SUBMIT_PROPOSAL: 'SUBMIT_PROPOSAL',
  CREATE_WORLD: 'CREATE_WORLD',
  EDIT_OWN_DRAFT: 'EDIT_OWN_DRAFT',
  EDIT_ANY_DRAFT: 'EDIT_ANY_DRAFT',
  EDIT_INITIAL_CANON: 'EDIT_INITIAL_CANON',
  EDIT_CANON_MODERATION_FIX: 'EDIT_CANON_MODERATION_FIX',
  VOTE_ON_PROPOSAL: 'VOTE_ON_PROPOSAL',
  EXECUTE_CANON_STATUS_AFTER_THRESHOLD: 'EXECUTE_CANON_STATUS_AFTER_THRESHOLD',
  REPORT_SPAM_ABUSE: 'REPORT_SPAM_ABUSE',
  MARK_SPAM_ABUSE: 'MARK_SPAM_ABUSE',
  COMMENT_ON_AI_WARNING: 'COMMENT_ON_AI_WARNING',
  RESOLVE_AI_WARNING_QUEUE: 'RESOLVE_AI_WARNING_QUEUE',
} as const;

export type WorldPermission = (typeof WORLD_PERMISSIONS)[keyof typeof WORLD_PERMISSIONS];

export const WORLD_ROLE_PERMISSIONS = {
  [WORLD_ROLES.READER]: [
    WORLD_PERMISSIONS.VIEW_PUBLIC_WORLD,
    WORLD_PERMISSIONS.VOTE_ON_PROPOSAL,
    WORLD_PERMISSIONS.REPORT_SPAM_ABUSE,
  ],
  [WORLD_ROLES.CONTRIBUTOR]: [
    WORLD_PERMISSIONS.VIEW_PUBLIC_WORLD,
    WORLD_PERMISSIONS.CREATE_LORE_DRAFT,
    WORLD_PERMISSIONS.SUBMIT_PROPOSAL,
    WORLD_PERMISSIONS.EDIT_OWN_DRAFT,
    WORLD_PERMISSIONS.VOTE_ON_PROPOSAL,
    WORLD_PERMISSIONS.REPORT_SPAM_ABUSE,
  ],
  [WORLD_ROLES.FOUNDER]: [
    WORLD_PERMISSIONS.VIEW_PUBLIC_WORLD,
    WORLD_PERMISSIONS.CREATE_LORE_DRAFT,
    WORLD_PERMISSIONS.SUBMIT_PROPOSAL,
    WORLD_PERMISSIONS.CREATE_WORLD,
    WORLD_PERMISSIONS.EDIT_OWN_DRAFT,
    WORLD_PERMISSIONS.EDIT_INITIAL_CANON,
    WORLD_PERMISSIONS.VOTE_ON_PROPOSAL,
    WORLD_PERMISSIONS.EXECUTE_CANON_STATUS_AFTER_THRESHOLD,
    WORLD_PERMISSIONS.REPORT_SPAM_ABUSE,
    WORLD_PERMISSIONS.COMMENT_ON_AI_WARNING,
  ],
  [WORLD_ROLES.CURATOR]: [
    WORLD_PERMISSIONS.VIEW_PUBLIC_WORLD,
    WORLD_PERMISSIONS.CREATE_LORE_DRAFT,
    WORLD_PERMISSIONS.SUBMIT_PROPOSAL,
    WORLD_PERMISSIONS.EDIT_OWN_DRAFT,
    WORLD_PERMISSIONS.EDIT_ANY_DRAFT,
    WORLD_PERMISSIONS.EDIT_CANON_MODERATION_FIX,
    WORLD_PERMISSIONS.VOTE_ON_PROPOSAL,
    WORLD_PERMISSIONS.EXECUTE_CANON_STATUS_AFTER_THRESHOLD,
    WORLD_PERMISSIONS.REPORT_SPAM_ABUSE,
    WORLD_PERMISSIONS.MARK_SPAM_ABUSE,
    WORLD_PERMISSIONS.RESOLVE_AI_WARNING_QUEUE,
  ],
} as const satisfies Record<WorldRole, readonly WorldPermission[]>;

export function roleHasWorldPermission(role: WorldRole, permission: WorldPermission) {
  return (WORLD_ROLE_PERMISSIONS[role] as readonly WorldPermission[]).includes(permission);
}
